### PR TITLE
docs: Add quotes to bool `setup_raid` value

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Review by indradhanush — APPROVED** [review]

**Review by rata — APPROVED** [review]
LGTM! :-D

Maybe we want to emphazise the use of quotes so it is not ignored by mistake?

**Review by invidian — CHANGES_REQUESTED** [review]
There is no explanation why there should be quotes. `os_version` does not have quotes and it's fine?

**Comment by surajssd** [comment]
I think this is a string value and having a quote around it only makes it explicit that this should not be confused to boolean!

**Comment by rata** [comment]
@surajssd @invidian it is explained here: https://www.terraform.io/docs/configuration-0-11/variables.html#booleans

Adding it makes sense, IMHO :)

**Comment by surajssd** [comment]
Thanks for finding that @rata 

I have seen this a lot in yamls of Kubernetes, while setting labels or while providing data in configmap. If you provide boolean weird parsing errors show up. Specially because the field was is of type string and user is providing plain boolean value as `true` or `false`. The only solution to this was putting double quotes around it and make it string.

**Review by invidian — APPROVED** [review]

**Pull request merged**
