### PR TITLE
docs: Improve setup_raid var documentation

### PR DESCRIPTION
**Pull request by johananl**
- Improve description phrasing.
- Remove quotes from boolean values for consistency.

### CODE REVIEW

**Comment by rata** [comment]
@johananl quotes for bools are needed, sadly, see this PR and this comment: https://github.com/kinvolk/lokomotive-kubernetes/pull/44#issuecomment-517660118

**Comment by johananl** [comment]
Then we should put quotes everywhere, not only on some of the lines:

https://github.com/kinvolk/lokomotive-kubernetes/blame/4b5174bfba533702382a55e186cd78030b721e2d/docs/flatcar-linux/packet.md#L313

**Comment by rata** [comment]
@johananl Yes :)

**Comment by johananl** [comment]
> @johananl quotes for bools are needed, sadly, see this PR and this comment: [#44 (comment)](https://github.com/kinvolk/lokomotive-kubernetes/pull/44#issuecomment-517660118)

Not needed anymore in TF 0.12.

**Review by rata — CHANGES_REQUESTED** [review]
The PR is so old that the description is no longer accurate. The `setup_raid_*` flags are mutually exclusive (i.e you can't set `setup_raid_hdd` and `setup_raid_sdd`). See terraform vars: https://github.com/kinvolk/lokomotive-kubernetes/blob/75569dc95f5ac95b360d7c0bbcc19284033da266/packet/flatcar-linux/kubernetes/workers/variables.tf#L117-L139

Can you update to reflect that?

As a side not, while being mutually exclusive is not useful, those flags never worked even in the commit that introduced them. IMHO, we might even want to remove them or avoid the flag maddness in some way. Created these issues to improve the situation in the past: #73 #74 #75.

**Comment by invidian** [comment]
@johananl can you please implement requested changes?

**Comment by johananl** [comment]
>Can you update to reflect that?

Done.

>As a side not, while being mutually exclusive is not useful, those flags never worked even in the commit that introduced them. IMHO, we might even want to remove them or avoid the flag maddness in some way. Created these issues to improve the situation in the past: #73 #74 #75.

I agree. This PR doesn't deal with the functionality however, only with the phrasing in the docs.

**Review by rata — APPROVED** [review]
Thanks! LGTM!

**Pull request merged**
