### PR TITLE
Packet: Allow to specify kubernetes version

### PR DESCRIPTION
**Pull request by miry**
Upgrade kubernetes to v1.14.3 and extract version to variables.

### CODE REVIEW

**Comment by rata** [comment]
We update the kubernetes version via terraform-render-bootkube, usually. Like here: https://github.com/kinvolk/terraform-render-bootkube/commit/a80eed2b6ac489243a6454dc2f46b17eefa7d84d

Would it be okay for you to update the kubernete version via the bootkube repo but not have a variable?

**Comment by miry** [comment]
In this way I removed duplication of usage kube version. You can change in one place, and everything related would be updated. It would remove human factor, that you should change in multiple places same value.

**Comment by rata** [comment]
Sure, but just to be clear: this shouldn't be changed without changing terraform-render-bootkube repo too, and changing the bootkube.tf in the module to use the new commit, IIUC.

As this is easy to script, I'm not sure it is worth and don't want to confuse the user thinking he can change the kubernetes version just changing that variable (as bootkube change is needed too, IIUC). It will also add more diff to typhoon, so not sure this is a clear win.

Let me ask others what they think and get back to you.

**Comment by miry** [comment]
@rata here is bootkube changes https://github.com/pubnative/lokomotive-kubernetes/blob/master/packet/flatcar-linux/kubernetes/bootkube.tf#L33

I forget to add it, let me updatte PR.

**Comment by miry** [comment]
updated PR

**Comment by rata** [comment]
I'm not sure this will work either, as when updating kubernetes we might have to do some changes on bootkube.

Furthermore, an example is just around the corner: it is needed to change bootkube for the 1.14 to 1.15 upgrade. And with this patch it will break.

The changelog here says hyperkube binary should chenge their names: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#apps (see the PR here: https://github.com/kubernetes/kubernetes/pull/76953). Therefore, we need to do something like this on terraform-render-bootkube when updating the kubernetes version: https://github.com/poseidon/terraform-render-bootkube/commit/62df9ad69cc0da35f47d40fa981370c4503ad581. If not, cluster creation will be broken.

I think the upgrade path that works, as I said, is: update terraform-render-bootkube, update the reference here to the new version terraform-render-bootkube, update the manifests too. This can be auto-generated/scripted.

Am I missing something?

What lead you to write the patch? To simplify changing the kubernetes version used?

**Comment by miry** [comment]
I see, so new bootkube would work only with version v1.15 and higher. 

But still it is not blocker to use variables for kube version. With this feature this repo is more independent from changes in terraform-render-bootkube. You would not need to update everytime module dependicies, and in same time have a new or old version of kube, with new changes of bootkube.

> What lead you to write the patch? To simplify changing the kubernetes version used?

I tried to upgrade from kube 1.14.1 to 1.14.3, and spent some time to find all places where I should apply changes. Then I came to bootkube module, that has different version. 
I use [Don't Repeat Yourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) practice in the code. We require changes in one place, for related things.

**Comment by rata** [comment]
> I see, so new bootkube would work only with version v1.15 and higher.

No, if the new bootkube, with that change, is made it will work with older Kubernetes versions too (all maintained versions). Just that those commands were deprecated and completely removed in 1.15, but the new commands already worked in older kubernetes versions. (there is a deprecation period in which kubernetes releases support both, until one is fully removed, to allow users to transition easily).

So, a new bootube with that change will work fine, even if we are using an older k8s version.

> But still it is not blocker to use variables for kube version. With this feature this repo is more independent from changes in terraform-render-bootkube. You would not need to update everytime 

The thing is: the repo is not totally independant and needs to be in sync with terraform-render-bootkube right now.
 
> > What lead you to write the patch? To simplify changing the kubernetes version used?
> 
> I tried to upgrade from kube 1.14.1 to 1.14.3, and spent some time to find all places where I should apply changes. Then I came to bootkube module, that has different version.
> I use [Don't Repeat Yourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) practice in the code. We require changes in one place, for related things.

I see a point on switching kubernetes releases on an easier way. But I must say I don't think it is really repeating ourselves if we can just do it with a script and meant to do it on a script or auto-generate it. Also, having a variable exposed to the user means the user can change it. But that will fail and create a bad user experience, the user might specify 1.15.0 and fail. I do not want to expose that to the user if it won't work reliably.

As there might be breaking changes (always some change is there) in new k8s releases and need to adapt, usually you support up to some version. Other tools, like kops, use compatibility matrix for example: https://github.com/kubernetes/kops#compatibility-matrix.

Right now we are doing some even simpler: this installs a particular kubernetes version (v1.14.1, for example). That is it for now.

I see value on changing kubernetes releases, for example, but right now it needs to be in sync with terraform-render-bootkube. Maybe it is easier to support just changing patch releases... But not sure we want to go down that route now, and just install one version for now?

**Comment by surajssd** [comment]
can we close this PR ?

**Comment by rata** [comment]
@miry friendly ping? :)

**Comment by miry** [comment]
@rata Sure, if you think it is ok, we can close.

**Pull request closed without merging**
